Add files via upload

diff --git a/rna-strain-match b/rna-strain-match
--- a/rna-strain-match
+++ b/rna-strain-match
@@ -100,6 +100,29 @@ elif [ ! -s "$bam" ] ; then
   print_usage
   echo "ERROR: $bam does not exist! Please enter a new NucSeq bam file."
   exit 1
+elif [ ! -s "$snps" ] ; then
+  print_usage
+  echo "ERROR: $snps does not exist! Please enter a new genotype matrix file."
+  exit 1
+elif [ ! -s "$pos" ] ; then
+  print_usage
+  echo "ERROR: $pos does not exist! Please enter a new SNP positions file."
+  exit 1
+elif [ ! -s "$bed" ] ; then
+  print_usage
+  echo "ERROR: $bed does not exist! Please enter a new SNP bed file."
+  exit 1
+fi
+
+if [[ $varMatch == "true" || $varMatch == "t" ]] && [ -z $strain ]; then
+  print_usage
+  echo "ERROR: no strain provided - varMatch requires a strain to compare to!"
+  echo "Please enter a strain in the configuration file"
+  exit 1
+elif [[ $varMatch == "true" || $varMatch == "t" ]] && [ -z $(head -n1 $snps | grep -ow $strain) ]; then
+  print_usage
+  echo "ERROR: provided strain, $strain, is not in genotype matrix file, $snps"
+  exit 1
 fi
 
 mkdir $o
@@ -137,7 +160,11 @@ echo "Parsing, formatting, and filtering data..."
 
 $Rscript ${dir}/match-strains.R ${o}/all-nuc.txt ${o}/${id} $snps $dp_cut $af_cut $f1
 
-if [ -z $keep ] ; then
+if [ -z $varMatch ]; then
+  $Rscript ${dir}/var-matching.R ${o}/all-nuc.txt ${o}/${id} $snps $strain $dp_cut $af_cut $f1
+fi
+
+if [[ $keep != "true" && $keep != "t" ]] ; then
   rm ${o}/all-nuc.txt
 fi
 
